function str = instrDB(task, english_on)

if english_on
    switch task
        case {'RewardTask', 'RewardDemo'}
            str = ['\nIn this exprtiment 6 circles will be displayed. ' ...
                '\nAnd there will be one bar in each circle. ' ...
                '\nThe task is to judge whether there is a horizontal or vertical bar. ' ...
                '\n' ...
                '\nPress z key for a horizontal bar.' ...
                '\nPress m key for a vertical bar.' ...
                '\n' ...
                '\nThere is only one target in each trial. ' ...
                '\nTry to press the key as soon as possible. ' ...
                '\nTime is limited and the reward is based on your response. ' ...
                '\n' ...
                '\n' ...
                '\nPress any key to continue.'];
        case 'rewardFeedback'
            str = ['\n + %.2f.' ...
                '\n' ...
                'Total: %.2f'];

        case 'rest'
            str = ['\nPlease rest for %f seconds.' ...
                '\n' ...
                '\nIf you want to proceed, press any button.'];
        otherwise
            str = ['Unknown task!'];
    end
else
    switch task
        case {'RewardTask', 'RewardDemo'}
            str = ['\n\n本实验中，会呈现6个圆形，每个圆形中都会有一个棒。' ...
                '\n\n任务就是在呈现的6个棒中找到垂直或水平的棒，请作出相应按键反应。' ...
                '\n\n' ...
                '\n\n如果发现棒是垂直的，请按键盘z。' ...
                '\n\n如果发现棒是水平的，请按键盘m。' ...
                '\n\n' ...
                '\n\n每一次呈现中只会有一个唯一的目标。' ...
                '\n\n要在保证正确的前提下尽可能快的作反应。' ...
                '\n\n' ...
                '\n\n反应有时间限制，并且会根据您的反应给予相应的奖赏。'];

        case 'rewardFeedback'
            str = ['\n + %.2f.' ...
                '\n' ...
                '总额: %.2f'];
        case 'rest'
            str = ['\n\n请休息%s秒。' ...
                '\n\n' ...
                '\n\n请按任意键继续。'];
        otherwise
            str = ['未知任务'];
    end

end
